### ISSUE TITLE
Dynamically create node sources/sinks

### ISSUE THREAD

**Issue by vgrcs** [aluntzer/gtknodes#12]
Hi,

I have tried to use a spinbutton to add new sources sockets after the call of the __init__() method.
The sockets are in fact created, but there are only drawn if the GtkNodes.Node is at position (0,0). See Figure 1.
The drag of the node fails to draw the sockets (Figure 2), but the lateral resize shows keeps the sockets visible (Figure 3)
![Figure-1](https://user-images.githubusercontent.com/7819300/183865064-723ee428-5dbb-4e58-ba24-02a45a1c8c77.png)
![Figure-2](https://user-images.githubusercontent.com/7819300/183865069-b1f1de47-d88d-4c11-b6bb-3be396e91789.png)
![Figure-3](https://user-images.githubusercontent.com/7819300/183865070-616be18a-b003-4ee9-8c44-30dddd5bebfa.png)

Best regards,
Vitor

**Comment by aluntzer** [comment]
Hi!

Could you attach a minimal example please? 

Thanks
Armin

**Comment by vgrcs** [comment]
Sure, here it is.
Thanks

[main.py.txt](https://github.com/aluntzer/gtknodes/files/9298951/main.py.txt)

**Comment by aluntzer** [comment]
This is a very weird bug. It appears as if the coordinates relative to the parent widget are not properly propagated when a widget is dynamically added and the relative origin is never updated. I will investigate in detail, but this may take some time.

Thanks
Armin

**Comment by vgrcs** [comment]
Hi, that's not a problem. A workaround will do for now. Here are a few further notes:
- I also noticed the absence of a "item_remove" method inside gtknode.h
- When a node is clicked it doesn't come to the foreground, only when it's dragged.

Many thanks in advance,
~Vitor

**Comment by aluntzer** [comment]
All done, including item_remove() method and node-to-foreground on click.

It turns out that the event window of the node socket item received a parent window different from the event window of the node when the node was already realized. The origin of this particular window was not moved when the node frame was dragged, because the node view had no reference of it, hence the coordinate origin never changed.
I don't known what the underlying cause of this behaviour is, but I suspect that a new GDK window is created and assigned if the widget has no parent window set when it is realized. However, setting a parent window early when adding a new node item fixes the issue.

best regards
Armin

**Comment by vgrcs** [comment]
Excellent!
Thank you
